package dev.uast;

import java.util.Map;
import java.util.Set;

public interface Data {
    Map<String, String> unicodeMap =
            Map.ofEntries(
                    Map.entry("a", "ā"),
                    Map.entry("i", "ī"),
                    Map.entry("u", "ū"),
                    Map.entry("r", "ṛ"),
                    Map.entry("ru", "ṝ"),
                    Map.entry("l", "ḷ"),
                    Map.entry("lu", "ḹ"),
                    Map.entry("ll", "ḻ"),
                    Map.entry("t", "ṭ"),
                    Map.entry("d", "ḍ"),
                    Map.entry("m", "ṃ"),
                    Map.entry("h", "ḥ"),
                    Map.entry("n", "ñ"),
                    Map.entry("nu", "ṅ"),
                    Map.entry("nl", "ṇ"),
                    Map.entry("su", "ś"),
                    Map.entry("sl", "ṣ"),
                    Map.entry(".", "।"),
                    Map.entry("..", "॥"),
                    Map.entry("au", "ã"));

    Set<String> unAspiratedConstants = Set.of("b", "c", "d", "g", "j", "k", "p", "t", "ḍ", "ṭ");

    Set<String> allowedSymbols = Set.of(",", "?", "!", "\"", "-", ":", "(", ")", "=", "|");

    Map<String, String> iastDataDict =
            Map.ofEntries(
                    Map.entry("०", "0"),
                    Map.entry("१", "1"),
                    Map.entry("२", "2"),
                    Map.entry("३", "3"),
                    Map.entry("४", "4"),
                    Map.entry("५", "5"),
                    Map.entry("६", "6"),
                    Map.entry("७", "7"),
                    Map.entry("८", "8"),
                    Map.entry("९", "9"),
                    Map.entry("ā", "a"),
                    Map.entry("ī", "i"),
                    Map.entry("ū", "u"),
                    Map.entry("ṛ", "r"),
                    Map.entry("ṝ", "ru"),
                    Map.entry("ḷ", "l"),
                    Map.entry("ḹ", "lu"),
                    Map.entry("ḻ", "ll"),
                    Map.entry("ṭ", "t"),
                    Map.entry("ḍ", "d"),
                    Map.entry("ṃ", "m"),
                    Map.entry("ḥ", "h"),
                    Map.entry("ñ", "n"),
                    Map.entry("ṅ", "nu"),
                    Map.entry("ṇ", "nl"),
                    Map.entry("ś", "su"),
                    Map.entry("ṣ", "sl"),
                    Map.entry("ऽ", "'"),
                    Map.entry("।", "."),
                    Map.entry("॥", ".."),
                    Map.entry("ॐ", "om"),
                    Map.entry("ã", "au"));

    Map<String, String> devanagariDataDict =
            Map.<String, String>ofEntries(
                    Map.entry("क", "k"),
                    Map.entry("ख", "kh"),
                    Map.entry("ग", "g"),
                    Map.entry("घ", "gh"),
                    Map.entry("ङ", "/nu/"),
                    Map.entry("च", "c"),
                    Map.entry("छ", "ch"),
                    Map.entry("ज", "j"),
                    Map.entry("झ", "jh"),
                    Map.entry("ञ", "/n/"),
                    Map.entry("ट", "/t/"),
                    Map.entry("ठ", "/t/h"),
                    Map.entry("ड", "/d/"),
                    Map.entry("ढ", "/d/h"),
                    Map.entry("ण", "/nl/"),
                    Map.entry("त", "t"),
                    Map.entry("थ", "th"),
                    Map.entry("द", "d"),
                    Map.entry("ध", "dh"),
                    Map.entry("न", "n"),
                    Map.entry("प", "p"),
                    Map.entry("फ", "ph"),
                    Map.entry("ब", "b"),
                    Map.entry("भ", "bh"),
                    Map.entry("म", "m"),
                    Map.entry("य", "y"),
                    Map.entry("र", "r"),
                    Map.entry("ल", "l"),
                    Map.entry("व", "v"),
                    Map.entry("श", "/su/"),
                    Map.entry("ष", "/sl/"),
                    Map.entry("स", "s"),
                    Map.entry("ह", "h"),
                    Map.entry("ळ", "/ll/"),
                    Map.entry("अ", "a"),
                    Map.entry("आ", "/a/"),
                    Map.entry("इ", "i"),
                    Map.entry("ई", "/i/"),
                    Map.entry("उ", "u"),
                    Map.entry("ऊ", "/u/"),
                    Map.entry("ऋ", "/r/"),
                    Map.entry("ॠ", "/ru/"),
                    Map.entry("ऌ", "/l/"),
                    Map.entry("ॡ", "/lu/"),
                    Map.entry("ए", "e"),
                    Map.entry("ऐ", "ai"),
                    Map.entry("ओ", "o"),
                    Map.entry("औ", "au"),
                    Map.entry("", "a"),
                    Map.entry("ा", "/a/"),
                    Map.entry("ि", "i"),
                    Map.entry("ी", "/i/"),
                    Map.entry("ु", "u"),
                    Map.entry("ू", "/u/"),
                    Map.entry("ृ", "/r/"),
                    Map.entry("ॄ", "/ru/"),
                    Map.entry("ॢ", "/l/"),
                    Map.entry("ॣ", "/lu/"),
                    Map.entry("े", "e"),
                    Map.entry("ै", "ai"),
                    Map.entry("ो", "o"),
                    Map.entry("ौ", "au"),
                    Map.entry("ं", "/m/"),
                    Map.entry("ः", "/h/"),
                    Map.entry("ँ", "/au/"),
                    Map.entry("्", "-"),
                    Map.entry("ऽ", "\\/'/\\"),
                    Map.entry("।", "\\/./\\"),
                    Map.entry("॥", "\\/../\\"),
                    Map.entry("ॐ", "\\/om/\\"),
                    Map.entry("०", "\\/0/\\"),
                    Map.entry("१", "\\/1/\\"),
                    Map.entry("२", "\\/2/\\"),
                    Map.entry("३", "\\/3/\\"),
                    Map.entry("४", "\\/4/\\"),
                    Map.entry("५", "\\/5/\\"),
                    Map.entry("६", "\\/6/\\"),
                    Map.entry("७", "\\/7/\\"),
                    Map.entry("८", "\\/8/\\"),
                    Map.entry("९", "\\/9/\\"));

    Map<String, String> slpDataDict =
            Map.<String, String>ofEntries(
                    Map.entry("a", "a"),
                    Map.entry("A", "ā"),
                    Map.entry("i", "i"),
                    Map.entry("I", "ī"),
                    Map.entry("u", "u"),
                    Map.entry("U", "ū"),
                    Map.entry("e", "e"),
                    Map.entry("E", "ai"),
                    Map.entry("o", "o"),
                    Map.entry("O", "au"),
                    Map.entry("f", "ṛ"),
                    Map.entry("F", "ṝ"),
                    Map.entry("x", "ḷ"),
                    Map.entry("X", "ḹ"),
                    Map.entry("L", "ḻ"),
                    Map.entry("|", "ḻh"),
                    Map.entry("k", "k"),
                    Map.entry("K", "kh"),
                    Map.entry("g", "g"),
                    Map.entry("G", "gh"),
                    Map.entry("N", "ṅ"),
                    Map.entry("c", "c"),
                    Map.entry("C", "ch"),
                    Map.entry("j", "j"),
                    Map.entry("J", "jh"),
                    Map.entry("Y", "ñ"),
                    Map.entry("w", "ṭ"),
                    Map.entry("W", "ṭh"),
                    Map.entry("q", "ḍ"),
                    Map.entry("Q", "ḍh"),
                    Map.entry("R", "ṇ"),
                    Map.entry("t", "t"),
                    Map.entry("T", "th"),
                    Map.entry("d", "d"),
                    Map.entry("D", "dh"),
                    Map.entry("n", "n"),
                    Map.entry("p", "p"),
                    Map.entry("P", "ph"),
                    Map.entry("b", "b"),
                    Map.entry("B", "bh"),
                    Map.entry("m", "m"),
                    Map.entry("M", "ṃ"),
                    Map.entry("H", "ḥ"),
                    Map.entry("y", "y"),
                    Map.entry("r", "r"),
                    Map.entry("l", "l"),
                    Map.entry("v", "v"),
                    Map.entry("S", "ś"),
                    Map.entry("z", "ṣ"),
                    Map.entry("s", "s"),
                    Map.entry("h", "h"),
                    Map.entry("'", "'"),
                    Map.entry("~", "ã"));

    Map<LangList, Map<LangMap, Map<String, String>>> charDict =
            Map.ofEntries(
                    Map.entry(
                            LangList.GU,
                            Map.ofEntries(
                                    Map.entry(
                                            LangMap.MISC,
                                            Map.ofEntries(
                                                    Map.entry("।", "."),
                                                    Map.entry("॥", ".."),
                                                    Map.entry("ऽ", "'"),
                                                    Map.entry("ॐ", "om"))),
                                    Map.entry(
                                            LangMap.NUMBERS,
                                            Map.ofEntries(
                                                    Map.entry("૦", "0"),
                                                    Map.entry("૧", "1"),
                                                    Map.entry("૨", "2"),
                                                    Map.entry("૩", "3"),
                                                    Map.entry("૪", "4"),
                                                    Map.entry("૫", "5"),
                                                    Map.entry("૬", "6"),
                                                    Map.entry("૭", "7"),
                                                    Map.entry("૮", "8"),
                                                    Map.entry("૯", "9"))),
                                    Map.entry(
                                            LangMap.VOWELS,
                                            Map.ofEntries(
                                                    Map.entry("a", "અ"),
                                                    Map.entry("ā", "આ"),
                                                    Map.entry("i", "ઇ"),
                                                    Map.entry("ī", "ઈ"),
                                                    Map.entry("u", "ઉ"),
                                                    Map.entry("ū", "ઊ"),
                                                    Map.entry("ṛ", "ઋ"),
                                                    Map.entry("e", "એ"),
                                                    Map.entry("ai", "ઐ"),
                                                    Map.entry("o", "ઓ"),
                                                    Map.entry("au", "ઔ"))),
                                    Map.entry(
                                            LangMap.VOWELSIGNS,
                                            Map.ofEntries(
                                                    Map.entry("a", ""),
                                                    Map.entry("ā", "ા"),
                                                    Map.entry("i", "િ"),
                                                    Map.entry("ī", "ી"),
                                                    Map.entry("u", "ુ"),
                                                    Map.entry("ū", "ૂ"),
                                                    Map.entry("ṛ", "ૃ"),
                                                    Map.entry("e", "ે"),
                                                    Map.entry("ai", "ૈ"),
                                                    Map.entry("o", "ો"),
                                                    Map.entry("au", "ૌ"),
                                                    Map.entry("ṃ", "ં"),
                                                    Map.entry("ḥ", "ઃ"),
                                                    Map.entry("ã", "ઁ"),
                                                    Map.entry("-", "્"))),
                                    Map.entry(
                                            LangMap.CONSONANTS,
                                            Map.ofEntries(
                                                    Map.entry("k", "ક"),
                                                    Map.entry("kh", "ખ"),
                                                    Map.entry("g", "ગ"),
                                                    Map.entry("gh", "ઘ"),
                                                    Map.entry("ṅ", "ઙ"),
                                                    Map.entry("c", "ચ"),
                                                    Map.entry("ch", "છ"),
                                                    Map.entry("j", "જ"),
                                                    Map.entry("jh", "ઝ"),
                                                    Map.entry("ñ", "ઞ"),
                                                    Map.entry("ṭ", "ટ"),
                                                    Map.entry("ṭh", "ઠ"),
                                                    Map.entry("ḍ", "ડ"),
                                                    Map.entry("ḍh", "ઢ"),
                                                    Map.entry("ṇ", "ણ"),
                                                    Map.entry("t", "ત"),
                                                    Map.entry("th", "થ"),
                                                    Map.entry("d", "દ"),
                                                    Map.entry("dh", "ધ"),
                                                    Map.entry("n", "ન"),
                                                    Map.entry("p", "પ"),
                                                    Map.entry("ph", "ફ"),
                                                    Map.entry("b", "બ"),
                                                    Map.entry("bh", "ભ"),
                                                    Map.entry("m", "મ"),
                                                    Map.entry("y", "ય"),
                                                    Map.entry("r", "ર"),
                                                    Map.entry("l", "લ"),
                                                    Map.entry("v", "વ"),
                                                    Map.entry("ś", "શ"),
                                                    Map.entry("ṣ", "ષ"),
                                                    Map.entry("s", "સ"),
                                                    Map.entry("h", "હ"),
                                                    Map.entry("ḻ", "ળ"))))),
                    Map.entry(
                            LangList.TA,
                            Map.ofEntries(
                                    Map.entry(
                                            LangMap.MISC,
                                            Map.ofEntries(
                                                    Map.entry("।", "."),
                                                    Map.entry("॥", ".."),
                                                    Map.entry("𑌽", "'"),
                                                    Map.entry("𑍐", "om"))),
                                    Map.entry(
                                            LangMap.NUMBERS,
                                            Map.ofEntries(
                                                    Map.entry("௦", "0"),
                                                    Map.entry("௧", "1"),
                                                    Map.entry("௨", "2"),
                                                    Map.entry("௩", "3"),
                                                    Map.entry("௪", "4"),
                                                    Map.entry("௫", "5"),
                                                    Map.entry("௬", "6"),
                                                    Map.entry("௭", "7"),
                                                    Map.entry("௮", "8"),
                                                    Map.entry("௯", "9"))),
                                    Map.entry(
                                            LangMap.VOWELS,
                                            Map.ofEntries(
                                                    Map.entry("a", "𑌅"),
                                                    Map.entry("ā", "𑌆"),
                                                    Map.entry("i", "𑌇"),
                                                    Map.entry("ī", "𑌈"),
                                                    Map.entry("u", "𑌉"),
                                                    Map.entry("ū", "𑌊"),
                                                    Map.entry("ṛ", "𑌋"),
                                                    Map.entry("ṝ", "𑍠"),
                                                    Map.entry("ḷ", "𑌌"),
                                                    Map.entry("ḹ", "𑍡"),
                                                    Map.entry("e", "𑌏"),
                                                    Map.entry("ai", "𑌐"),
                                                    Map.entry("o", "𑌓"),
                                                    Map.entry("au", "𑌔"))),
                                    Map.entry(
                                            LangMap.VOWELSIGNS,
                                            Map.ofEntries(
                                                    Map.entry("a", ""),
                                                    Map.entry("ā", "𑌾"),
                                                    Map.entry("i", "𑌿"),
                                                    Map.entry("ī", "𑍀"),
                                                    Map.entry("u", "𑍁"),
                                                    Map.entry("ū", "𑍂"),
                                                    Map.entry("ṛ", "𑍃"),
                                                    Map.entry("ṝ", "𑍄"),
                                                    Map.entry("ḷ", "𑍢"),
                                                    Map.entry("ḹ", "𑍣"),
                                                    Map.entry("e", "𑍇"),
                                                    Map.entry("ai", "𑍈"),
                                                    Map.entry("o", "𑍋"),
                                                    Map.entry("au", "𑍗"),
                                                    Map.entry("ṃ", "𑌂"),
                                                    Map.entry("ḥ", "𑌃"),
                                                    Map.entry("ã", "𑌁"),
                                                    Map.entry("-", "𑍍"))),
                                    Map.entry(
                                            LangMap.CONSONANTS,
                                            Map.ofEntries(
                                                    Map.entry("k", "𑌕"),
                                                    Map.entry("kh", "𑌖"),
                                                    Map.entry("g", "𑌗"),
                                                    Map.entry("gh", "𑌘"),
                                                    Map.entry("ṅ", "𑌙"),
                                                    Map.entry("c", "𑌚"),
                                                    Map.entry("ch", "𑌛"),
                                                    Map.entry("j", "𑌜"),
                                                    Map.entry("jh", "𑌝"),
                                                    Map.entry("ñ", "𑌞"),
                                                    Map.entry("ṭ", "𑌟"),
                                                    Map.entry("ṭh", "𑌠"),
                                                    Map.entry("ḍ", "𑌡"),
                                                    Map.entry("ḍh", "𑌢"),
                                                    Map.entry("ṇ", "𑌣"),
                                                    Map.entry("t", "𑌤"),
                                                    Map.entry("th", "𑌥"),
                                                    Map.entry("d", "𑌦"),
                                                    Map.entry("dh", "𑌧"),
                                                    Map.entry("n", "𑌨"),
                                                    Map.entry("p", "𑌪"),
                                                    Map.entry("ph", "𑌫"),
                                                    Map.entry("b", "𑌬"),
                                                    Map.entry("bh", "𑌭"),
                                                    Map.entry("m", "𑌮"),
                                                    Map.entry("y", "𑌯"),
                                                    Map.entry("r", "𑌰"),
                                                    Map.entry("l", "𑌲"),
                                                    Map.entry("v", "𑌵"),
                                                    Map.entry("ś", "𑌶"),
                                                    Map.entry("ṣ", "𑌷"),
                                                    Map.entry("s", "𑌸"),
                                                    Map.entry("h", "𑌹"),
                                                    Map.entry("ḻ", "𑌳"))))),
                    Map.entry(
                            LangList.ML,
                            Map.ofEntries(
                                    Map.entry(
                                            LangMap.MISC,
                                            Map.ofEntries(
                                                    Map.entry("।", "."),
                                                    Map.entry("॥", ".."),
                                                    Map.entry("ഽ", "'"),
                                                    Map.entry("ഓം", "om"))),
                                    Map.entry(
                                            LangMap.NUMBERS,
                                            Map.ofEntries(
                                                    Map.entry("൦", "0"),
                                                    Map.entry("൧", "1"),
                                                    Map.entry("൨", "2"),
                                                    Map.entry("൩", "3"),
                                                    Map.entry("൪", "4"),
                                                    Map.entry("൫", "5"),
                                                    Map.entry("൬", "6"),
                                                    Map.entry("൭", "7"),
                                                    Map.entry("൮", "8"),
                                                    Map.entry("൯", "9"))),
                                    Map.entry(
                                            LangMap.VOWELS,
                                            Map.ofEntries(
                                                    Map.entry("a", "അ"),
                                                    Map.entry("ā", "ആ"),
                                                    Map.entry("i", "ഇ"),
                                                    Map.entry("ī", "ഈ"),
                                                    Map.entry("u", "ഉ"),
                                                    Map.entry("ū", "ഊ"),
                                                    Map.entry("ṛ", "ഋ"),
                                                    Map.entry("ṝ", "ൠ"),
                                                    Map.entry("ḷ", "ഌ"),
                                                    Map.entry("ḹ", "ൡ"),
                                                    Map.entry("e", "എ"),
                                                    Map.entry("ai", "ഐ"),
                                                    Map.entry("o", "ഒ"),
                                                    Map.entry("au", "ഔ"))),
                                    Map.entry(
                                            LangMap.VOWELSIGNS,
                                            Map.ofEntries(
                                                    Map.entry("a", ""),
                                                    Map.entry("ā", "ാ"),
                                                    Map.entry("i", "ി"),
                                                    Map.entry("ī", "ീ"),
                                                    Map.entry("u", "ു"),
                                                    Map.entry("ū", "ൂ"),
                                                    Map.entry("ṛ", "ൃ"),
                                                    Map.entry("ṝ", "ൄ"),
                                                    Map.entry("ḷ", "ൢ"),
                                                    Map.entry("ḹ", "ൣ"),
                                                    Map.entry("e", "െ"),
                                                    Map.entry("ai", "ൈ"),
                                                    Map.entry("o", "ൊ"),
                                                    Map.entry("au", "ൗ"),
                                                    Map.entry("ṃ", "ം"),
                                                    Map.entry("ḥ", "ഃ"),
                                                    Map.entry("ã", "ഁ"),
                                                    Map.entry("-", "്"))),
                                    Map.entry(
                                            LangMap.CONSONANTS,
                                            Map.ofEntries(
                                                    Map.entry("k", "ക"),
                                                    Map.entry("kh", "ഖ"),
                                                    Map.entry("g", "ഗ"),
                                                    Map.entry("gh", "ഘ"),
                                                    Map.entry("ṅ", "ങ"),
                                                    Map.entry("c", "ച"),
                                                    Map.entry("ch", "ഛ"),
                                                    Map.entry("j", "ജ"),
                                                    Map.entry("jh", "ഝ"),
                                                    Map.entry("ñ", "ഞ"),
                                                    Map.entry("ṭ", "ട"),
                                                    Map.entry("ṭh", "ഠ"),
                                                    Map.entry("ḍ", "ഡ"),
                                                    Map.entry("ḍh", "ഢ"),
                                                    Map.entry("ṇ", "ണ"),
                                                    Map.entry("t", "ത"),
                                                    Map.entry("th", "ഥ"),
                                                    Map.entry("d", "ദ"),
                                                    Map.entry("dh", "ധ"),
                                                    Map.entry("n", "ന"),
                                                    Map.entry("p", "പ"),
                                                    Map.entry("ph", "ഫ"),
                                                    Map.entry("b", "ബ"),
                                                    Map.entry("bh", "ഭ"),
                                                    Map.entry("m", "മ"),
                                                    Map.entry("y", "യ"),
                                                    Map.entry("r", "ര"),
                                                    Map.entry("l", "ല"),
                                                    Map.entry("v", "വ"),
                                                    Map.entry("ś", "ശ"),
                                                    Map.entry("ṣ", "ഷ"),
                                                    Map.entry("s", "സ"),
                                                    Map.entry("h", "ഹ"),
                                                    Map.entry("ḻ", "ള"))))),
                    Map.entry(
                            LangList.TE,
                            Map.ofEntries(
                                    Map.entry(
                                            LangMap.MISC,
                                            Map.ofEntries(
                                                    Map.entry("।", "."),
                                                    Map.entry("॥", ".."),
                                                    Map.entry("ఽ", "'"),
                                                    Map.entry("ఓం", "om"))),
                                    Map.entry(
                                            LangMap.NUMBERS,
                                            Map.ofEntries(
                                                    Map.entry("౦", "0"),
                                                    Map.entry("౧", "1"),
                                                    Map.entry("౨", "2"),
                                                    Map.entry("౩", "3"),
                                                    Map.entry("౪", "4"),
                                                    Map.entry("౫", "5"),
                                                    Map.entry("౬", "6"),
                                                    Map.entry("౭", "7"),
                                                    Map.entry("౮", "8"),
                                                    Map.entry("౯", "9"))),
                                    Map.entry(
                                            LangMap.VOWELS,
                                            Map.ofEntries(
                                                    Map.entry("a", "అ"),
                                                    Map.entry("ā", "ఆ"),
                                                    Map.entry("i", "ఇ"),
                                                    Map.entry("ī", "ఈ"),
                                                    Map.entry("u", "ఉ"),
                                                    Map.entry("ū", "ఊ"),
                                                    Map.entry("ṛ", "ఋ"),
                                                    Map.entry("ṝ", "ౠ"),
                                                    Map.entry("ḷ", "ఌ"),
                                                    Map.entry("ḹ", "ౡ"),
                                                    Map.entry("e", "ఎ"),
                                                    Map.entry("ai", "ఐ"),
                                                    Map.entry("o", "ఒ"),
                                                    Map.entry("au", "ఔ"))),
                                    Map.entry(
                                            LangMap.VOWELSIGNS,
                                            Map.ofEntries(
                                                    Map.entry("a", ""),
                                                    Map.entry("ā", "ా"),
                                                    Map.entry("i", "ి"),
                                                    Map.entry("ī", "ీ"),
                                                    Map.entry("u", "ు"),
                                                    Map.entry("ū", "ూ"),
                                                    Map.entry("ṛ", "ృ"),
                                                    Map.entry("ṝ", "ౄ"),
                                                    Map.entry("ḷ", "ౢ"),
                                                    Map.entry("ḹ", "ౣ"),
                                                    Map.entry("e", "ె"),
                                                    Map.entry("ai", "ై"),
                                                    Map.entry("o", "ొ"),
                                                    Map.entry("au", "ౌ"),
                                                    Map.entry("ṃ", "ం"),
                                                    Map.entry("ḥ", "ః"),
                                                    Map.entry("ã", "ఁ"),
                                                    Map.entry("-", "్"))),
                                    Map.entry(
                                            LangMap.CONSONANTS,
                                            Map.ofEntries(
                                                    Map.entry("k", "క"),
                                                    Map.entry("kh", "ఖ"),
                                                    Map.entry("g", "గ"),
                                                    Map.entry("gh", "ఘ"),
                                                    Map.entry("ṅ", "ఙ"),
                                                    Map.entry("c", "చ"),
                                                    Map.entry("ch", "ఛ"),
                                                    Map.entry("j", "జ"),
                                                    Map.entry("jh", "ఝ"),
                                                    Map.entry("ñ", "ఞ"),
                                                    Map.entry("ṭ", "ట"),
                                                    Map.entry("ṭh", "ఠ"),
                                                    Map.entry("ḍ", "డ"),
                                                    Map.entry("ḍh", "ఢ"),
                                                    Map.entry("ṇ", "ణ"),
                                                    Map.entry("t", "త"),
                                                    Map.entry("th", "థ"),
                                                    Map.entry("d", "ద"),
                                                    Map.entry("dh", "ధ"),
                                                    Map.entry("n", "న"),
                                                    Map.entry("p", "ప"),
                                                    Map.entry("ph", "ఫ"),
                                                    Map.entry("b", "బ"),
                                                    Map.entry("bh", "భ"),
                                                    Map.entry("m", "మ"),
                                                    Map.entry("y", "య"),
                                                    Map.entry("r", "ర"),
                                                    Map.entry("l", "ల"),
                                                    Map.entry("v", "వ"),
                                                    Map.entry("ś", "శ"),
                                                    Map.entry("ṣ", "ష"),
                                                    Map.entry("s", "స"),
                                                    Map.entry("h", "హ"),
                                                    Map.entry("ḻ", "ళ"))))),
                    Map.entry(
                            LangList.KN,
                            Map.ofEntries(
                                    Map.entry(
                                            LangMap.MISC,
                                            Map.ofEntries(
                                                    Map.entry("।", "."),
                                                    Map.entry("॥", ".."),
                                                    Map.entry("ಽ", "'"),
                                                    Map.entry("ಓಂ", "om"))),
                                    Map.entry(
                                            LangMap.NUMBERS,
                                            Map.ofEntries(
                                                    Map.entry("೦", "0"),
                                                    Map.entry("೧", "1"),
                                                    Map.entry("೨", "2"),
                                                    Map.entry("೩", "3"),
                                                    Map.entry("೪", "4"),
                                                    Map.entry("೫", "5"),
                                                    Map.entry("೬", "6"),
                                                    Map.entry("೭", "7"),
                                                    Map.entry("೮", "8"),
                                                    Map.entry("೯", "9"))),
                                    Map.entry(
                                            LangMap.VOWELS,
                                            Map.ofEntries(
                                                    Map.entry("a", "ಅ"),
                                                    Map.entry("ā", "ಆ"),
                                                    Map.entry("i", "ಇ"),
                                                    Map.entry("ī", "ಈ"),
                                                    Map.entry("u", "ಉ"),
                                                    Map.entry("ū", "ಊ"),
                                                    Map.entry("ṛ", "ಋ"),
                                                    Map.entry("ṝ", "ೠ"),
                                                    Map.entry("ḷ", "ಌ"),
                                                    Map.entry("ḹ", "ೡ"),
                                                    Map.entry("e", "ಎ"),
                                                    Map.entry("ai", "ಐ"),
                                                    Map.entry("o", "ಒ"),
                                                    Map.entry("au", "ಔ"))),
                                    Map.entry(
                                            LangMap.VOWELSIGNS,
                                            Map.ofEntries(
                                                    Map.entry("a", ""),
                                                    Map.entry("ā", "ಾ"),
                                                    Map.entry("i", "ಿ"),
                                                    Map.entry("ī", "ೀ"),
                                                    Map.entry("u", "ು"),
                                                    Map.entry("ū", "ೂ"),
                                                    Map.entry("ṛ", "ೃ"),
                                                    Map.entry("ṝ", "ೄ"),
                                                    Map.entry("ḷ", "ೢ"),
                                                    Map.entry("ḹ", "ೣ"),
                                                    Map.entry("e", "ೆ"),
                                                    Map.entry("ai", "ೈ"),
                                                    Map.entry("o", "ೊ"),
                                                    Map.entry("au", "ೌ"),
                                                    Map.entry("ṃ", "ಂ"),
                                                    Map.entry("ḥ", "ಃ"),
                                                    Map.entry("ã", "ಁ"),
                                                    Map.entry("-", "್"))),
                                    Map.entry(
                                            LangMap.CONSONANTS,
                                            Map.ofEntries(
                                                    Map.entry("k", "ಕ"),
                                                    Map.entry("kh", "ಖ"),
                                                    Map.entry("g", "ಗ"),
                                                    Map.entry("gh", "ಘ"),
                                                    Map.entry("ṅ", "ಙ"),
                                                    Map.entry("c", "ಚ"),
                                                    Map.entry("ch", "ಛ"),
                                                    Map.entry("j", "ಜ"),
                                                    Map.entry("jh", "ಝ"),
                                                    Map.entry("ñ", "ಞ"),
                                                    Map.entry("ṭ", "ಟ"),
                                                    Map.entry("ṭh", "ಠ"),
                                                    Map.entry("ḍ", "ಡ"),
                                                    Map.entry("ḍh", "ಢ"),
                                                    Map.entry("ṇ", "ಣ"),
                                                    Map.entry("t", "ತ"),
                                                    Map.entry("th", "ಥ"),
                                                    Map.entry("d", "ದ"),
                                                    Map.entry("dh", "ಧ"),
                                                    Map.entry("n", "ನ"),
                                                    Map.entry("p", "ಪ"),
                                                    Map.entry("ph", "ಫ"),
                                                    Map.entry("b", "ಬ"),
                                                    Map.entry("bh", "ಭ"),
                                                    Map.entry("m", "ಮ"),
                                                    Map.entry("y", "ಯ"),
                                                    Map.entry("r", "ರ"),
                                                    Map.entry("l", "ಲ"),
                                                    Map.entry("v", "ವ"),
                                                    Map.entry("ś", "ಶ"),
                                                    Map.entry("ṣ", "ಷ"),
                                                    Map.entry("s", "ಸ"),
                                                    Map.entry("h", "ಹ"),
                                                    Map.entry("ḻ", "ಳ"))))),
                    Map.entry(
                            LangList.OR,
                            Map.ofEntries(
                                    Map.entry(
                                            LangMap.MISC,
                                            Map.ofEntries(
                                                    Map.entry("।", "."),
                                                    Map.entry("॥", ".."),
                                                    Map.entry("ଽ", "'"),
                                                    Map.entry("ଓଁ", "om"))),
                                    Map.entry(
                                            LangMap.NUMBERS,
                                            Map.ofEntries(
                                                    Map.entry("୦", "0"),
                                                    Map.entry("୧", "1"),
                                                    Map.entry("୨", "2"),
                                                    Map.entry("୩", "3"),
                                                    Map.entry("୪", "4"),
                                                    Map.entry("୫", "5"),
                                                    Map.entry("୬", "6"),
                                                    Map.entry("୭", "7"),
                                                    Map.entry("୮", "8"),
                                                    Map.entry("୯", "9"))),
                                    Map.entry(
                                            LangMap.VOWELS,
                                            Map.ofEntries(
                                                    Map.entry("a", "ଅ"),
                                                    Map.entry("ā", "ଆ"),
                                                    Map.entry("i", "ଇ"),
                                                    Map.entry("ī", "ଈ"),
                                                    Map.entry("u", "ଉ"),
                                                    Map.entry("ū", "ଊ"),
                                                    Map.entry("ṛ", "ଋ"),
                                                    Map.entry("ṝ", "ୠ"),
                                                    Map.entry("ḷ", "ଌ"),
                                                    Map.entry("ḹ", "ୡ"),
                                                    Map.entry("e", "ଏ"),
                                                    Map.entry("ai", "ଐ"),
                                                    Map.entry("o", "ଓ"),
                                                    Map.entry("au", "ଔ"))),
                                    Map.entry(
                                            LangMap.VOWELSIGNS,
                                            Map.ofEntries(
                                                    Map.entry("a", ""),
                                                    Map.entry("ā", "ା"),
                                                    Map.entry("i", "ି"),
                                                    Map.entry("ī", "ୀ"),
                                                    Map.entry("u", "ୁ"),
                                                    Map.entry("ū", "ୂ"),
                                                    Map.entry("ṛ", "ୃ"),
                                                    Map.entry("ṝ", "ୄ"),
                                                    Map.entry("ḷ", "ୢ"),
                                                    Map.entry("ḹ", "ୣ"),
                                                    Map.entry("e", "େ"),
                                                    Map.entry("ai", "ୈ"),
                                                    Map.entry("o", "ୋ"),
                                                    Map.entry("au", "ୌ"),
                                                    Map.entry("ṃ", "ଂ"),
                                                    Map.entry("ḥ", "ଃ"),
                                                    Map.entry("ã", "ଁ"),
                                                    Map.entry("-", "୍"))),
                                    Map.entry(
                                            LangMap.CONSONANTS,
                                            Map.ofEntries(
                                                    Map.entry("k", "କ"),
                                                    Map.entry("kh", "ଖ"),
                                                    Map.entry("g", "ଗ"),
                                                    Map.entry("gh", "ଘ"),
                                                    Map.entry("ṅ", "ଙ"),
                                                    Map.entry("c", "ଚ"),
                                                    Map.entry("ch", "ଛ"),
                                                    Map.entry("j", "ଜ"),
                                                    Map.entry("jh", "ଝ"),
                                                    Map.entry("ñ", "ଞ"),
                                                    Map.entry("ṭ", "ଟ"),
                                                    Map.entry("ṭh", "ଠ"),
                                                    Map.entry("ḍ", "ଡ"),
                                                    Map.entry("ḍh", "ଢ"),
                                                    Map.entry("ṇ", "ଣ"),
                                                    Map.entry("t", "ତ"),
                                                    Map.entry("th", "ଥ"),
                                                    Map.entry("d", "ଦ"),
                                                    Map.entry("dh", "ଧ"),
                                                    Map.entry("n", "ନ"),
                                                    Map.entry("p", "ପ"),
                                                    Map.entry("ph", "ଫ"),
                                                    Map.entry("b", "ବ"),
                                                    Map.entry("bh", "ଭ"),
                                                    Map.entry("m", "ମ"),
                                                    Map.entry("y", "ୟ"),
                                                    Map.entry("r", "ର"),
                                                    Map.entry("l", "ଲ"),
                                                    Map.entry("v", "ୱ"),
                                                    Map.entry("ś", "ଶ"),
                                                    Map.entry("ṣ", "ଷ"),
                                                    Map.entry("s", "ସ"),
                                                    Map.entry("h", "ହ"),
                                                    Map.entry("ḻ", "ଳ"))))),
                    Map.entry(
                            LangList.SA,
                            Map.ofEntries(
                                    Map.entry(
                                            LangMap.MISC,
                                            Map.ofEntries(
                                                    Map.entry("।", "."),
                                                    Map.entry("॥", ".."),
                                                    Map.entry("ऽ", "'"),
                                                    Map.entry("ॐ", "om"))),
                                    Map.entry(
                                            LangMap.NUMBERS,
                                            Map.ofEntries(
                                                    Map.entry("०", "0"),
                                                    Map.entry("१", "1"),
                                                    Map.entry("२", "2"),
                                                    Map.entry("३", "3"),
                                                    Map.entry("४", "4"),
                                                    Map.entry("५", "5"),
                                                    Map.entry("६", "6"),
                                                    Map.entry("७", "7"),
                                                    Map.entry("८", "8"),
                                                    Map.entry("९", "9"))),
                                    Map.entry(
                                            LangMap.VOWELS,
                                            Map.ofEntries(
                                                    Map.entry("a", "अ"),
                                                    Map.entry("ā", "आ"),
                                                    Map.entry("i", "इ"),
                                                    Map.entry("ī", "ई"),
                                                    Map.entry("u", "उ"),
                                                    Map.entry("ū", "ऊ"),
                                                    Map.entry("ṛ", "ऋ"),
                                                    Map.entry("ṝ", "ॠ"),
                                                    Map.entry("ḷ", "ऌ"),
                                                    Map.entry("ḹ", "ॡ"),
                                                    Map.entry("e", "ए"),
                                                    Map.entry("ai", "ऐ"),
                                                    Map.entry("o", "ओ"),
                                                    Map.entry("au", "औ"))),
                                    Map.entry(
                                            LangMap.VOWELSIGNS,
                                            Map.ofEntries(
                                                    Map.entry("a", ""),
                                                    Map.entry("ā", "ा"),
                                                    Map.entry("i", "ि"),
                                                    Map.entry("ī", "ी"),
                                                    Map.entry("u", "ु"),
                                                    Map.entry("ū", "ू"),
                                                    Map.entry("ṛ", "ृ"),
                                                    Map.entry("ṝ", "ॄ"),
                                                    Map.entry("ḷ", "ॢ"),
                                                    Map.entry("ḹ", "ॣ"),
                                                    Map.entry("e", "े"),
                                                    Map.entry("ai", "ै"),
                                                    Map.entry("o", "ो"),
                                                    Map.entry("au", "ौ"),
                                                    Map.entry("ṃ", "ं"),
                                                    Map.entry("ḥ", "ः"),
                                                    Map.entry("ã", "ँ"),
                                                    Map.entry("-", "्"))),
                                    Map.entry(
                                            LangMap.CONSONANTS,
                                            Map.ofEntries(
                                                    Map.entry("k", "क"),
                                                    Map.entry("kh", "ख"),
                                                    Map.entry("g", "ग"),
                                                    Map.entry("gh", "घ"),
                                                    Map.entry("ṅ", "ङ"),
                                                    Map.entry("c", "च"),
                                                    Map.entry("ch", "छ"),
                                                    Map.entry("j", "ज"),
                                                    Map.entry("jh", "झ"),
                                                    Map.entry("ñ", "ञ"),
                                                    Map.entry("ṭ", "ट"),
                                                    Map.entry("ṭh", "ठ"),
                                                    Map.entry("ḍ", "ड"),
                                                    Map.entry("ḍh", "ढ"),
                                                    Map.entry("ṇ", "ण"),
                                                    Map.entry("t", "त"),
                                                    Map.entry("th", "थ"),
                                                    Map.entry("d", "द"),
                                                    Map.entry("dh", "ध"),
                                                    Map.entry("n", "न"),
                                                    Map.entry("p", "प"),
                                                    Map.entry("ph", "फ"),
                                                    Map.entry("b", "ब"),
                                                    Map.entry("bh", "भ"),
                                                    Map.entry("m", "म"),
                                                    Map.entry("y", "य"),
                                                    Map.entry("r", "र"),
                                                    Map.entry("l", "ल"),
                                                    Map.entry("v", "व"),
                                                    Map.entry("ś", "श"),
                                                    Map.entry("ṣ", "ष"),
                                                    Map.entry("s", "स"),
                                                    Map.entry("h", "ह"),
                                                    Map.entry("ḻ", "ळ"))))));

    Map<LangList, Map<String, String>> scripts =
            Map.ofEntries(
                    Map.entry(
                            LangList.GU,
                            Map.<String, String>ofEntries(
                                    Map.entry("।", "।"),
                                    Map.entry("॥", "॥"),
                                    Map.entry("ઽ", "ऽ"),
                                    Map.entry("ॐ", "ओम्"),
                                    Map.entry("૦", "०"),
                                    Map.entry("૧", "१"),
                                    Map.entry("૨", "२"),
                                    Map.entry("૩", "३"),
                                    Map.entry("૪", "४"),
                                    Map.entry("૫", "५"),
                                    Map.entry("૬", "६"),
                                    Map.entry("૭", "७"),
                                    Map.entry("૮", "८"),
                                    Map.entry("૯", "९"),
                                    Map.entry("અ", "अ"),
                                    Map.entry("આ", "आ"),
                                    Map.entry("ઇ", "इ"),
                                    Map.entry("ઈ", "ई"),
                                    Map.entry("ઉ", "उ"),
                                    Map.entry("ઊ", "ऊ"),
                                    Map.entry("ઋ", "ऋ"),
                                    Map.entry("ૠ", "ॠ"),
                                    Map.entry("ઌ", "ऌ"),
                                    Map.entry("ૡ", "ॡ"),
                                    Map.entry("એ", "ए"),
                                    Map.entry("ઐ", "ऐ"),
                                    Map.entry("ઓ", "ओ"),
                                    Map.entry("ઔ", "औ"),
                                    Map.entry("ા", "ा"),
                                    Map.entry("િ", "ि"),
                                    Map.entry("ી", "ी"),
                                    Map.entry("ુ", "ु"),
                                    Map.entry("ૂ", "ू"),
                                    Map.entry("ૃ", "ृ"),
                                    Map.entry("ૄ", "ॄ"),
                                    Map.entry("ૢ", "ॢ"),
                                    Map.entry("ૣ", "ॣ"),
                                    Map.entry("ે", "े"),
                                    Map.entry("ૈ", "ै"),
                                    Map.entry("ો", "ो"),
                                    Map.entry("ૌ", "ौ"),
                                    Map.entry("ં", "ं"),
                                    Map.entry("ઃ", "ः"),
                                    Map.entry("ઁ", "ँ"),
                                    Map.entry("્", "्"),
                                    Map.entry("ક", "क"),
                                    Map.entry("ખ", "ख"),
                                    Map.entry("ગ", "ग"),
                                    Map.entry("ઘ", "घ"),
                                    Map.entry("ઙ", "ङ"),
                                    Map.entry("ચ", "च"),
                                    Map.entry("છ", "छ"),
                                    Map.entry("જ", "ज"),
                                    Map.entry("ઝ", "झ"),
                                    Map.entry("ઞ", "ञ"),
                                    Map.entry("ટ", "ट"),
                                    Map.entry("ઠ", "ठ"),
                                    Map.entry("ડ", "ड"),
                                    Map.entry("ઢ", "ढ"),
                                    Map.entry("ણ", "ण"),
                                    Map.entry("ત", "त"),
                                    Map.entry("થ", "थ"),
                                    Map.entry("દ", "द"),
                                    Map.entry("ધ", "ध"),
                                    Map.entry("ન", "न"),
                                    Map.entry("પ", "प"),
                                    Map.entry("ફ", "फ"),
                                    Map.entry("બ", "ब"),
                                    Map.entry("ભ", "भ"),
                                    Map.entry("મ", "म"),
                                    Map.entry("ય", "य"),
                                    Map.entry("ર", "र"),
                                    Map.entry("લ", "ल"),
                                    Map.entry("વ", "व"),
                                    Map.entry("શ", "श"),
                                    Map.entry("ષ", "ष"),
                                    Map.entry("સ", "स"),
                                    Map.entry("હ", "ह"),
                                    Map.entry("ળ", "ळ"))),
                    Map.entry(
                            LangList.OR,
                            Map.<String, String>ofEntries(
                                    Map.entry("।", "।"),
                                    Map.entry("॥", "॥"),
                                    Map.entry("ଽ", "ऽ"),
                                    Map.entry("ଓଁ", "ओम्"),
                                    Map.entry("୦", "०"),
                                    Map.entry("୧", "१"),
                                    Map.entry("୨", "२"),
                                    Map.entry("୩", "३"),
                                    Map.entry("୪", "४"),
                                    Map.entry("୫", "५"),
                                    Map.entry("୬", "६"),
                                    Map.entry("୭", "७"),
                                    Map.entry("୮", "८"),
                                    Map.entry("୯", "९"),
                                    Map.entry("ଅ", "अ"),
                                    Map.entry("ଆ", "आ"),
                                    Map.entry("ଇ", "इ"),
                                    Map.entry("ଈ", "ई"),
                                    Map.entry("ଉ", "उ"),
                                    Map.entry("ଊ", "ऊ"),
                                    Map.entry("ଋ", "ऋ"),
                                    Map.entry("ୠ", "ॠ"),
                                    Map.entry("ଌ", "ऌ"),
                                    Map.entry("ୡ", "ॡ"),
                                    Map.entry("ଏ", "ए"),
                                    Map.entry("ଐ", "ऐ"),
                                    Map.entry("ଓ", "ओ"),
                                    Map.entry("ଔ", "औ"),
                                    Map.entry("ା", "ा"),
                                    Map.entry("ି", "ि"),
                                    Map.entry("ୀ", "ी"),
                                    Map.entry("ୁ", "ु"),
                                    Map.entry("ୂ", "ू"),
                                    Map.entry("ୃ", "ृ"),
                                    Map.entry("ୄ", "ॄ"),
                                    Map.entry("ୢ", "ॢ"),
                                    Map.entry("ୣ", "ॣ"),
                                    Map.entry("େ", "े"),
                                    Map.entry("ୈ", "ै"),
                                    Map.entry("ୋ", "ो"),
                                    Map.entry("ୌ", "ौ"),
                                    Map.entry("ଂ", "ं"),
                                    Map.entry("ଃ", "ः"),
                                    Map.entry("ଁ", "ँ"),
                                    Map.entry("୍", "्"),
                                    Map.entry("କ", "क"),
                                    Map.entry("ଖ", "ख"),
                                    Map.entry("ଗ", "ग"),
                                    Map.entry("ଘ", "घ"),
                                    Map.entry("ଙ", "ङ"),
                                    Map.entry("ଚ", "च"),
                                    Map.entry("ଛ", "छ"),
                                    Map.entry("ଜ", "ज"),
                                    Map.entry("ଝ", "झ"),
                                    Map.entry("ଞ", "ञ"),
                                    Map.entry("ଟ", "ट"),
                                    Map.entry("ଠ", "ठ"),
                                    Map.entry("ଡ", "ड"),
                                    Map.entry("ଢ", "ढ"),
                                    Map.entry("ଣ", "ण"),
                                    Map.entry("ତ", "त"),
                                    Map.entry("ଥ", "थ"),
                                    Map.entry("ଦ", "द"),
                                    Map.entry("ଧ", "ध"),
                                    Map.entry("ନ", "न"),
                                    Map.entry("ପ", "प"),
                                    Map.entry("ଫ", "फ"),
                                    Map.entry("ବ", "ब"),
                                    Map.entry("ଭ", "भ"),
                                    Map.entry("ମ", "म"),
                                    Map.entry("ୟ", "य"),
                                    Map.entry("ର", "र"),
                                    Map.entry("ଲ", "ल"),
                                    Map.entry("ୱ", "व"),
                                    Map.entry("ଶ", "श"),
                                    Map.entry("ଷ", "ष"),
                                    Map.entry("ସ", "स"),
                                    Map.entry("ହ", "ह"),
                                    Map.entry("ଳ", "ळ"))),
                    Map.entry(
                            LangList.KN,
                            Map.<String, String>ofEntries(
                                    Map.entry("।", "।"),
                                    Map.entry("॥", "॥"),
                                    Map.entry("ಽ", "ऽ"),
                                    Map.entry("ಓಂ", "ओम्"),
                                    Map.entry("೦", "०"),
                                    Map.entry("೧", "१"),
                                    Map.entry("೨", "२"),
                                    Map.entry("೩", "३"),
                                    Map.entry("೪", "४"),
                                    Map.entry("೫", "५"),
                                    Map.entry("೬", "६"),
                                    Map.entry("೭", "७"),
                                    Map.entry("೮", "८"),
                                    Map.entry("೯", "९"),
                                    Map.entry("ಅ", "अ"),
                                    Map.entry("ಆ", "आ"),
                                    Map.entry("ಇ", "इ"),
                                    Map.entry("ಈ", "ई"),
                                    Map.entry("ಉ", "उ"),
                                    Map.entry("ಊ", "ऊ"),
                                    Map.entry("ಋ", "ऋ"),
                                    Map.entry("ೠ", "ॠ"),
                                    Map.entry("ಌ", "ऌ"),
                                    Map.entry("ೡ", "ॡ"),
                                    Map.entry("ಎ", "ए"),
                                    Map.entry("ಐ", "ऐ"),
                                    Map.entry("ಒ", "ओ"),
                                    Map.entry("ಔ", "औ"),
                                    Map.entry("ಾ", "ा"),
                                    Map.entry("ಿ", "ि"),
                                    Map.entry("ೀ", "ी"),
                                    Map.entry("ು", "ु"),
                                    Map.entry("ೂ", "ू"),
                                    Map.entry("ೃ", "ृ"),
                                    Map.entry("ೄ", "ॄ"),
                                    Map.entry("ೢ", "ॢ"),
                                    Map.entry("ೣ", "ॣ"),
                                    Map.entry("ೆ", "े"),
                                    Map.entry("ೈ", "ै"),
                                    Map.entry("ೊ", "ो"),
                                    Map.entry("ೌ", "ौ"),
                                    Map.entry("ಂ", "ं"),
                                    Map.entry("ಃ", "ः"),
                                    Map.entry("ಁ", "ँ"),
                                    Map.entry("್", "्"),
                                    Map.entry("ಕ", "क"),
                                    Map.entry("ಖ", "ख"),
                                    Map.entry("ಗ", "ग"),
                                    Map.entry("ಘ", "घ"),
                                    Map.entry("ಙ", "ङ"),
                                    Map.entry("ಚ", "च"),
                                    Map.entry("ಛ", "छ"),
                                    Map.entry("ಜ", "ज"),
                                    Map.entry("ಝ", "झ"),
                                    Map.entry("ಞ", "ञ"),
                                    Map.entry("ಟ", "ट"),
                                    Map.entry("ಠ", "ठ"),
                                    Map.entry("ಡ", "ड"),
                                    Map.entry("ಢ", "ढ"),
                                    Map.entry("ಣ", "ण"),
                                    Map.entry("ತ", "त"),
                                    Map.entry("ಥ", "थ"),
                                    Map.entry("ದ", "द"),
                                    Map.entry("ಧ", "ध"),
                                    Map.entry("ನ", "न"),
                                    Map.entry("ಪ", "प"),
                                    Map.entry("ಫ", "फ"),
                                    Map.entry("ಬ", "ब"),
                                    Map.entry("ಭ", "भ"),
                                    Map.entry("ಮ", "म"),
                                    Map.entry("ಯ", "य"),
                                    Map.entry("ರ", "र"),
                                    Map.entry("ಲ", "ल"),
                                    Map.entry("ವ", "व"),
                                    Map.entry("ಶ", "श"),
                                    Map.entry("ಷ", "ष"),
                                    Map.entry("ಸ", "स"),
                                    Map.entry("ಹ", "ह"),
                                    Map.entry("ಳ", "ळ"))),
                    Map.entry(
                            LangList.TE,
                            Map.<String, String>ofEntries(
                                    Map.entry("।", "।"),
                                    Map.entry("॥", "॥"),
                                    Map.entry("ఽ", "ऽ"),
                                    Map.entry("ఓం", "ओम्"),
                                    Map.entry("౦", "०"),
                                    Map.entry("౧", "१"),
                                    Map.entry("౨", "२"),
                                    Map.entry("౩", "३"),
                                    Map.entry("౪", "४"),
                                    Map.entry("౫", "५"),
                                    Map.entry("౬", "६"),
                                    Map.entry("౭", "७"),
                                    Map.entry("౮", "८"),
                                    Map.entry("౯", "९"),
                                    Map.entry("అ", "अ"),
                                    Map.entry("ఆ", "आ"),
                                    Map.entry("ఇ", "इ"),
                                    Map.entry("ఈ", "ई"),
                                    Map.entry("ఉ", "उ"),
                                    Map.entry("ఊ", "ऊ"),
                                    Map.entry("ఋ", "ऋ"),
                                    Map.entry("ౠ", "ॠ"),
                                    Map.entry("ఌ", "ऌ"),
                                    Map.entry("ౡ", "ॡ"),
                                    Map.entry("ఎ", "ए"),
                                    Map.entry("ఐ", "ऐ"),
                                    Map.entry("ఒ", "ओ"),
                                    Map.entry("ఔ", "औ"),
                                    Map.entry("ా", "ा"),
                                    Map.entry("ి", "ि"),
                                    Map.entry("ీ", "ी"),
                                    Map.entry("ు", "ु"),
                                    Map.entry("ూ", "ू"),
                                    Map.entry("ృ", "ृ"),
                                    Map.entry("ౄ", "ॄ"),
                                    Map.entry("ౢ", "ॢ"),
                                    Map.entry("ౣ", "ॣ"),
                                    Map.entry("ె", "े"),
                                    Map.entry("ై", "ै"),
                                    Map.entry("ొ", "ो"),
                                    Map.entry("ౌ", "ौ"),
                                    Map.entry("ం", "ं"),
                                    Map.entry("ః", "ः"),
                                    Map.entry("ఁ", "ँ"),
                                    Map.entry("్", "्"),
                                    Map.entry("క", "क"),
                                    Map.entry("ఖ", "ख"),
                                    Map.entry("గ", "ग"),
                                    Map.entry("ఘ", "घ"),
                                    Map.entry("ఙ", "ङ"),
                                    Map.entry("చ", "च"),
                                    Map.entry("ఛ", "छ"),
                                    Map.entry("జ", "ज"),
                                    Map.entry("ఝ", "झ"),
                                    Map.entry("ఞ", "ञ"),
                                    Map.entry("ట", "ट"),
                                    Map.entry("ఠ", "ठ"),
                                    Map.entry("డ", "ड"),
                                    Map.entry("ఢ", "ढ"),
                                    Map.entry("ణ", "ण"),
                                    Map.entry("త", "त"),
                                    Map.entry("థ", "थ"),
                                    Map.entry("ద", "द"),
                                    Map.entry("ధ", "ध"),
                                    Map.entry("న", "न"),
                                    Map.entry("ప", "प"),
                                    Map.entry("ఫ", "फ"),
                                    Map.entry("బ", "ब"),
                                    Map.entry("భ", "भ"),
                                    Map.entry("మ", "म"),
                                    Map.entry("య", "य"),
                                    Map.entry("ర", "र"),
                                    Map.entry("ల", "ल"),
                                    Map.entry("వ", "व"),
                                    Map.entry("శ", "श"),
                                    Map.entry("ష", "ष"),
                                    Map.entry("స", "स"),
                                    Map.entry("హ", "ह"),
                                    Map.entry("ళ", "ळ"))),
                    Map.entry(
                            LangList.ML,
                            Map.<String, String>ofEntries(
                                    Map.entry("।", "।"),
                                    Map.entry("॥", "॥"),
                                    Map.entry("ഽ", "ऽ"),
                                    Map.entry("ഓം", "ओम्"),
                                    Map.entry("൦", "०"),
                                    Map.entry("൧", "१"),
                                    Map.entry("൨", "२"),
                                    Map.entry("൩", "३"),
                                    Map.entry("൪", "४"),
                                    Map.entry("൫", "५"),
                                    Map.entry("൬", "६"),
                                    Map.entry("൭", "७"),
                                    Map.entry("൮", "८"),
                                    Map.entry("൯", "९"),
                                    Map.entry("അ", "अ"),
                                    Map.entry("ആ", "आ"),
                                    Map.entry("ഇ", "इ"),
                                    Map.entry("ഈ", "ई"),
                                    Map.entry("ഉ", "उ"),
                                    Map.entry("ഊ", "ऊ"),
                                    Map.entry("ഋ", "ऋ"),
                                    Map.entry("ൠ", "ॠ"),
                                    Map.entry("ഌ", "ऌ"),
                                    Map.entry("ൡ", "ॡ"),
                                    Map.entry("എ", "ए"),
                                    Map.entry("ഐ", "ऐ"),
                                    Map.entry("ഒ", "ओ"),
                                    Map.entry("ഔ", "औ"),
                                    Map.entry("ാ", "ा"),
                                    Map.entry("ി", "ि"),
                                    Map.entry("ീ", "ी"),
                                    Map.entry("ു", "ु"),
                                    Map.entry("ൂ", "ू"),
                                    Map.entry("ൃ", "ृ"),
                                    Map.entry("ൄ", "ॄ"),
                                    Map.entry("ൢ", "ॢ"),
                                    Map.entry("ൣ", "ॣ"),
                                    Map.entry("െ", "े"),
                                    Map.entry("ൈ", "ै"),
                                    Map.entry("ൊ", "ो"),
                                    Map.entry("ൗ", "ौ"),
                                    Map.entry("ം", "ं"),
                                    Map.entry("ഃ", "ः"),
                                    Map.entry("ഁ", "ँ"),
                                    Map.entry("്", "्"),
                                    Map.entry("ക", "क"),
                                    Map.entry("ഖ", "ख"),
                                    Map.entry("ഗ", "ग"),
                                    Map.entry("ഘ", "घ"),
                                    Map.entry("ങ", "ङ"),
                                    Map.entry("ച", "च"),
                                    Map.entry("ഛ", "छ"),
                                    Map.entry("ജ", "ज"),
                                    Map.entry("ഝ", "झ"),
                                    Map.entry("ഞ", "ञ"),
                                    Map.entry("ട", "ट"),
                                    Map.entry("ഠ", "ठ"),
                                    Map.entry("ഡ", "ड"),
                                    Map.entry("ഢ", "ढ"),
                                    Map.entry("ണ", "ण"),
                                    Map.entry("ത", "त"),
                                    Map.entry("ഥ", "थ"),
                                    Map.entry("ദ", "द"),
                                    Map.entry("ധ", "ध"),
                                    Map.entry("ന", "न"),
                                    Map.entry("പ", "प"),
                                    Map.entry("ഫ", "फ"),
                                    Map.entry("ബ", "ब"),
                                    Map.entry("ഭ", "भ"),
                                    Map.entry("മ", "म"),
                                    Map.entry("യ", "य"),
                                    Map.entry("ര", "र"),
                                    Map.entry("ല", "ल"),
                                    Map.entry("വ", "व"),
                                    Map.entry("ശ", "श"),
                                    Map.entry("ഷ", "ष"),
                                    Map.entry("സ", "स"),
                                    Map.entry("ഹ", "ह"),
                                    Map.entry("ള", "ळ"))),
                    Map.entry(
                            LangList.TA,
                            Map.<String, String>ofEntries(
                                    Map.entry("।", "।"),
                                    Map.entry("॥", "॥"),
                                    Map.entry("𑌽", "ऽ"),
                                    Map.entry("𑍐", "ओम्"),
                                    Map.entry("௦", "०"),
                                    Map.entry("௧", "१"),
                                    Map.entry("௨", "२"),
                                    Map.entry("௩", "३"),
                                    Map.entry("௪", "४"),
                                    Map.entry("௫", "५"),
                                    Map.entry("௬", "६"),
                                    Map.entry("௭", "७"),
                                    Map.entry("௮", "८"),
                                    Map.entry("௯", "९"),
                                    Map.entry("𑌅", "अ"),
                                    Map.entry("𑌆", "आ"),
                                    Map.entry("𑌇", "इ"),
                                    Map.entry("𑌈", "ई"),
                                    Map.entry("𑌉", "उ"),
                                    Map.entry("𑌊", "ऊ"),
                                    Map.entry("𑌋", "ऋ"),
                                    Map.entry("𑍠", "ॠ"),
                                    Map.entry("𑌌", "ऌ"),
                                    Map.entry("𑍡", "ॡ"),
                                    Map.entry("𑌏", "ए"),
                                    Map.entry("𑌐", "ऐ"),
                                    Map.entry("𑌓", "ओ"),
                                    Map.entry("𑌔", "औ"),
                                    Map.entry("𑌾", "ा"),
                                    Map.entry("𑌿", "ि"),
                                    Map.entry("𑍀", "ी"),
                                    Map.entry("𑍁", "ु"),
                                    Map.entry("𑍂", "ू"),
                                    Map.entry("𑍃", "ृ"),
                                    Map.entry("𑍄", "ॄ"),
                                    Map.entry("𑍢", "ॢ"),
                                    Map.entry("𑍣", "ॣ"),
                                    Map.entry("𑍇", "े"),
                                    Map.entry("𑍈", "ै"),
                                    Map.entry("𑍋", "ो"),
                                    Map.entry("𑍗", "ौ"),
                                    Map.entry("𑌂", "ं"),
                                    Map.entry("𑌃", "ः"),
                                    Map.entry("𑌁", "ँ"),
                                    Map.entry("𑍍", "्"),
                                    Map.entry("𑌕", "क"),
                                    Map.entry("𑌖", "ख"),
                                    Map.entry("𑌗", "ग"),
                                    Map.entry("𑌘", "घ"),
                                    Map.entry("𑌙", "ङ"),
                                    Map.entry("𑌚", "च"),
                                    Map.entry("𑌛", "छ"),
                                    Map.entry("𑌜", "ज"),
                                    Map.entry("𑌝", "झ"),
                                    Map.entry("𑌞", "ञ"),
                                    Map.entry("𑌟", "ट"),
                                    Map.entry("𑌠", "ठ"),
                                    Map.entry("𑌡", "ड"),
                                    Map.entry("𑌢", "ढ"),
                                    Map.entry("𑌣", "ण"),
                                    Map.entry("𑌤", "त"),
                                    Map.entry("𑌥", "थ"),
                                    Map.entry("𑌦", "द"),
                                    Map.entry("𑌧", "ध"),
                                    Map.entry("𑌨", "न"),
                                    Map.entry("𑌪", "प"),
                                    Map.entry("𑌫", "फ"),
                                    Map.entry("𑌬", "ब"),
                                    Map.entry("𑌭", "भ"),
                                    Map.entry("𑌮", "म"),
                                    Map.entry("𑌯", "य"),
                                    Map.entry("𑌰", "र"),
                                    Map.entry("𑌲", "ल"),
                                    Map.entry("𑌵", "व"),
                                    Map.entry("𑌶", "श"),
                                    Map.entry("𑌷", "ष"),
                                    Map.entry("𑌸", "स"),
                                    Map.entry("𑌹", "ह"),
                                    Map.entry("𑌳", "ळ"))),
                    Map.entry(LangList.SA, Map.ofEntries()));
}
